branch-defaults:
  master:
    environment: doug-net-dev
    group_suffix: null
global:
  application_name: doug-net
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-1
  profile: eb-cli
  sc: git
